### ISSUE TITLE
`tag_file` does not work for folders

### ISSUE THREAD

**Issue by Luux** [Raudius/files_scripts#134]
Trying to perform `tag_file` on a folder results in `Cannot get property of non-object. Raudius\Luar\Interpreter\LuarObject\Reference`

As `tag_file_unassign` also supports folders, it would be great if they are also supported for `tag_file` as there does not seem to be another option to tag folders within a script.

**Comment by Raudius** [comment]
Thanks for the report.

I have fixed it for version `3.1.2`

**Comment by Luux** [comment]
@Raudius Hey there, thanks for the quick PR. Unfortunately, it still does not work.

```
local tags = tags_find({id="103"})  
if (#tags == 1) then  
  tag_file(get_input_files()[1], tags[1])
  add_message("Tag found: ", "success")
end  
```

Works for a file, but if I run it with a directory as input, the tag does not get assigned.

**Comment by Raudius** [comment]
Looks like something went wrong with the release process since the fix does not appear to be included.

I will make a new release tonight
